version: '3'
services:
  nginx:
    build:
      context: ./
      dockerfile: ./requirements/nginx/Dockerfile
    ports:
      - "443:443"
    restart: always
  mariadb:
    env_file:
      ./.env
    build:
      context: ./
      dockerfile: ./requirements/mariadb/Dockerfile
    ports:
      - "3306" 
