version: '3'
services:

  nginx:
    networks:
      - inception
    container_name: nginx
    build:
      context: ./
      dockerfile: ./requirements/nginx/Dockerfile
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/wordpress
    depends_on:
      - wordpress
    restart: always

  mariadb:
    networks:
      - inception
    container_name: mariadb
    env_file:
      .env
    build:
      context: ./
      dockerfile: ./requirements/mariadb/Dockerfile
    expose:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

  wordpress:
    networks:
        - inception
    container_name: wordpress
    env_file:
      .env
    build:
      context: ./
      dockerfile: ./requirements/wordpress/Dockerfile
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/wordpress
    restart: always
    expose:
      - "9000"

networks:
  inception:
    driver: bridge
volumes:
  wp_data:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/ljerinec/dataInception/wordpress'
  mariadb_data:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/ljerinec/dataInception/mariadb'
